# Keras Basics

We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

In [1]:
import numpy as np

## Dataset

We will use the famous Iris Data set.
_____
More info on the data set:
https://en.wikipedia.org/wiki/Iris_flower_data_set

## Reading in the Data Set

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
y = iris.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [10]:
y = to_categorical(y)

In [11]:
y.shape

(150, 3)

In [12]:
#y

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object = MinMaxScaler()

In [17]:
scaler_object.fit(X_train)

MinMaxScaler()

In [18]:
scaled_X_train = scaler_object.transform(X_train)

In [19]:
scaled_X_test = scaler_object.transform(X_test)

In [20]:
X_train.max()

7.7

In [21]:
scaled_X_train.max()

1.0

In [23]:
#X_train

In [24]:
#scaled_X_train

## Building the Network with Keras

Let's build a simple neural network!

In [25]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


## Fit (Train) the Model

In [29]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 1.0667 - accuracy: 0.3100
Epoch 2/150
 - 0s - loss: 1.0580 - accuracy: 0.3100
Epoch 3/150
 - 0s - loss: 1.0496 - accuracy: 0.3100
Epoch 4/150
 - 0s - loss: 1.0413 - accuracy: 0.3200
Epoch 5/150
 - 0s - loss: 1.0325 - accuracy: 0.3200
Epoch 6/150
 - 0s - loss: 1.0233 - accuracy: 0.3400
Epoch 7/150
 - 0s - loss: 1.0133 - accuracy: 0.3500
Epoch 8/150
 - 0s - loss: 1.0033 - accuracy: 0.3600
Epoch 9/150
 - 0s - loss: 0.9931 - accuracy: 0.3800
Epoch 10/150
 - 0s - loss: 0.9827 - accuracy: 0.4200
Epoch 11/150
 - 0s - loss: 0.9720 - accuracy: 0.5100
Epoch 12/150
 - 0s - loss: 0.9615 - accuracy: 0.5400
Epoch 13/150
 - 0s - loss: 0.9511 - accuracy: 0.5900
Epoch 14/150
 - 0s - loss: 0.9409 - accuracy: 0.6100
Epoch 15/150
 - 0s - loss: 0.9310 - accuracy: 0.6300
Epoch 16/150
 - 0s - loss: 0.9215 - accuracy: 0.6300
Epoch 17/150
 - 0s - loss: 0.9115 - accuracy: 0.6400
Epoch 18/150
 - 0s - loss: 0.9021 - accuracy: 0.6400
Epoch 19/150
 - 0s - loss: 0.8923 - accuracy: 0.6400
Ep

## Predicting New Unseen Data

In [28]:
#scaled_X_test

In [48]:
# Spits out probabilities by default.
# model.predict(scaled_X_test)

In [30]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision.

In [31]:
model.metrics_names

['loss', 'accuracy']

In [32]:
model.evaluate(x=scaled_X_test,y=y_test)
model.evaluate(x=scaled_X_test, y=y_test)

50/50 [==============================] - 0s 111us/step


[0.3577307343482971, 0.9399999976158142]

In [33]:
from sklearn.metrics import confusion_matrix,classification_report

In [34]:
predictions = model.predict_classes(scaled_X_test)

In [35]:
predictions

array([1, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [36]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [37]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 12,  3],
       [ 0,  0, 16]])

In [38]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.80      0.89        15
           2       0.84      1.00      0.91        16

    accuracy                           0.94        50
   macro avg       0.95      0.93      0.93        50
weighted avg       0.95      0.94      0.94        50



## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [39]:
model.save('myfirstmodel.h5')

In [40]:
from keras.models import load_model

In [41]:
newmodel = load_model('myfirstmodel.h5')

In [42]:
newmodel.predict_classes(X_test)

array([2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 2, 2, 2, 2, 2])